name: GondalKits
version: '1.2'
main: dev.thatlukinhasguy.gondalkits.Main
commands:
  createkit:
    permission: gondalkits.command.createkit
    aliases: [makekit, ckit]
  deletekit:
    permission: gondalkits.command.deletekit
    aliases: [delkit, purgekit]
  kit:
    permission: gondalkits.command.kit
  kits:
    permission: gondalkits.command.kits
    aliases: [listkits]

permissions:
  gondalkits.command.createkit:
    default: op
  gondalkits.command.deletekit:
    default: op
  gondalkits.command.kit:
    default: op
  gondalkits.command.kits:
    default: op